### ISSUE TITLE
Saves not transferring back and forth (Windows and Android)

### ISSUE THREAD

**Issue by Murasakikalla** [blake502/balatro-mobile-maker#107]
The installation worked perfectly and transferred my initial save. However, when I am now trying to transfer my saves either way (from mobile or from steam), after I hit Y on the prompt, it just shuts the terminal down and doesn't show what it is supposed to. The save transference does not work either, I have tried it thrice both ways.

I have turned Steam cloud saves off as well. Any way to ensure the terminal doesnt shut down and it actually executes the command?

**Comment by WokenClick** [comment]
Did you fix this? I'm having the same issue. Using version 0.8.3 on Windows, everything seems to work fine but the folders created on my PC when trying to transfer saves from Android to PC are just empty.
