### ISSUE TITLE
Don't have the permission to download the file

### ISSUE THREAD

**Issue by garyhe231** [blake502/balatro-mobile-maker#109]
Hi, not sure if this is related. I recently downloaded the latest version 0.8.3 and generated a new ipa file to have the latest Balatro Steam update. However, when I use the alt store to install the ipa it has an error saying "don't have the permission to download the file". I tried the earlier version ipa and it works well. I was using the win x64 version of the maker. Thank you!

**Comment by garyhe231** [comment]
Here is the error message:

Balatro could not be downloaded. You don’t have permission.

To view or change permissions, select the item in the Finder and choose File > Get Info.

**Comment by namquang93** [comment]
I think I have the same issue. I tried another IPA and it installed fine.

![Image](https://github.com/user-attachments/assets/26f64986-25a9-4e2f-9f43-3b81c44be24f)
