### ISSUE TITLE
Import saves from older versions of patch? 

### ISSUE THREAD

**Issue by franzmcfreya** [blake502/balatro-mobile-maker#23]
I didn't notice the newer version has disabled the option to make the saves accessible and I used it previously on 0.3 beta. Now patching with the latest release, 0.6 the older saves can no longer be used, I don't have root so I can't access both the accessible saves folder and internal folder. Not sure what you guys can do about it I just want to suggest:

1. leaving the option there for users who already use the former method or 
2. allow the importer to search through the accessible folder(trying to import currently just pulls bunch of empty files.)

Please let me know if anything needs clarification.

**Comment by blake502** [comment]
I'll look into this, but unfortunately this one may be written off as "that's beta software for ya" haha. I'll do some testing and see what I can come up with. That said, I think that patch is still in the code-- just commented out. If you're up for compiling it yourself, you can enable that patch again.

**Comment by franzmcfreya** [comment]
Yeah that's understandable, hope something can be done though. Not sure I'll be able to compile it but I'll definitely take a look at it. Thanks.

**Comment by franzmcfreya** [comment]
> Trying to pull with adb is giving me empty directories, and when I do adb backup com.unofficial.balatro the backup.ab is 1kb and won't open.

Yeah it's pulls empty directories because it's trying to get the saves from the internal folder which you of course don't use and hence there's no files to pull.
Unfortunately couldn't get around to modifying the patch myself(yet). So I guess we'll just have to wait and see what the devs come up with

**Comment by blake502** [comment]
I've added the optional command line argument `--enable-external-storage-patch` to beta-0.7.3

Give it a shot, it should let you keep using the patch formerly known as "accessible saves"

**Comment by blake502** [comment]
I'll go ahead and close this issue, but I can re-open it if it gives you trouble.
Have a great day!

**Comment by franzmcfreya** [comment]
Oh I didn't notice, been busy past few days, I'll try it out, and yeah I guess there's no reason to keep the issue open. Only one question, if I try to pull the saves will it search through that folder as well? If so that'll be awesome as it'd remove the need for that patch. It's fine if it doesn't though it's alright ig. I don't know if you'll see this since it's closed so hope you don't mind CC: @blake502

**Comment by fronc** [comment]
@blake502 how does accessible saves get... "accessed"... for non-root users? Is it possible?

My game is saved using that patch, but I don't have an SD card in my S24 Ultra. Is it possible to still pull the save file?

**Comment by blake502** [comment]
> Oh I didn't notice, been busy past few days, I'll try it out, and yeah I guess there's no reason to keep the issue open. Only one question, if I try to pull the saves will it search through that folder as well? If so that'll be awesome as it'd remove the need for that patch. It's fine if it doesn't though it's alright ig. I don't know if you'll see this since it's closed so hope you don't mind CC: @blake502

At this point, it does not. But that may change.

**Comment by fronc** [comment]
I really appreciate the quick reply, but one follow-up:
>>You can "access" the folder, but it will appear empty unless you use ADB.
I have access to ADB, just not root. When I try any commands it seems i'm just getting empty files, though. Assuming I used the accessible saves patch, could you tell me what adb commands I should try to extract the save data? Or am I still misunderstanding something critical here (i.e., root is still necessary with ADB)?

Thanks again!
