### ISSUE TITLE
Mac / Linux support for the tool

### ISSUE THREAD

**Issue by valknight** [blake502/balatro-mobile-maker#25]
I noticed this tool is restricted to Windows, requiring a VM for Mac / Linux folks to use the project.

The `Balatro.love` file is found inside our installation folders on macOS, so the process is actually very similar - we would just need alternative commands to execute. I tested, and the project does build with a migration to C# Core - although, nothing works due to many assumptions of being Windows only.

If you are open to it, I'm happy to work on a PR with some sweeping refactors to get this working on macOS and Linux, as well as modularize the patch process. I can imagine this tool will likely be useful even with the official release, as the game can likely be patched to install PC modloaders, and be able to run beta versions of the game; so I imagine the work won't be for naught.

**Comment by valknight** [comment]
Just to add to the compatibility here - I dropped 1.01c's Balatro.love onto a Windows PC, and just renamed it to Balatro.exe for the tool to pick up - and it runs identically to an IPA generated from the Windows build of the game.

![Screenshot 2024-04-14 at 02 17 26](https://github.com/blake502/balatro-apk-maker/assets/16143037/865165a2-a7eb-478a-ae79-6edf6297a944)

**Comment by blake502** [comment]
I'm certainly open to moving to .NET Core. I never anticipated so many folks to use the tool that cross-platform compatibility would be necessary. You're welcome to take this on, but I work quick-- so I just might beat you to it haha.

**Comment by blake502** [comment]
I've made a .NET Core project in a private branch. Once I get the multi-platform build process worked out, I'll seek some help sorting out all the platform-specific code.

**Comment by valknight** [comment]
Ah, oops, I've been doing a big refactor! I was about to open a PR now, because I've made changes to move a lot of stuff out into a Constants section - such that we can perform conditional compilation. Give me two secs to get the PR live.

**Comment by valknight** [comment]
Just got a PR live :) It's a lot of refactoring, C# modernisation, and prep for modernisation.

As for multi-plat build process, you could likely do this via GitHub actions. For a lot of my work right now, we make use of a lot of dotnet tooling via Actions - I can take a look at getting actions setup to run automated builds across multiple platforms.

**Comment by Enderteck** [comment]
Thx for the improvement, 
I did a Steam Guide to run the Game on Linux natively and this tool will be great once I can use it on my Linux PC to play on mobile !

**Comment by CUexter** [comment]
will there be github actions to build linux and mac versions of the executable ?

**Comment by CUexter** [comment]
I tried building in linux, it still needs a lot of work to make it work on linux, particularly this used cmd and installed a lot of stuff in the windows way

**Comment by antipatico** [comment]
I rewrote this tool in python, it runs on linux and should be compatible with mac too. You can give it a try until this project fully supports linux / mac: https://github.com/antipatico/balatromobile

**Comment by CUexter** [comment]
@antipatico i tried it but unfortunately there seems to be some problem on my side, i will write a bug report soon. It is related to the scaling of the gui.

**Comment by Enderteck** [comment]
> I rewrote this tool in python, it runs on linux and should be compatible with mac too. You can give it a try until this project fully supports linux / mac: https://github.com/antipatico/balatromobile

I works on Linux. Very easy to install with pip too !

https://github.com/antipatico/balatromobile

**Comment by blake502** [comment]
@antipatico @CUexter @Enderteck
No hard feelings, but I'm removing these comments since they aren't really relevant to this particular issue on this particular project.

**Comment by blake502** [comment]
I've begun implementing a platform layer to break out all the platform-specific code. That way, we can do something like this:
```
    public static void usePython(string args)
    {
        if (isWindows)
            CommandLine("python\\python.exe " + args);

        if (isOSX) { /*...*/ }

        if (isLinux) { /*...*/ }
    }
```

Things are going to get a little uglier before they get prettier, because I'm more interested in function over form-- at least at the moment. But this should put us in a good spot to implement Linux and MacOS compatibility with relative ease.

**Comment by blake502** [comment]
We're in a _really_ good position with this now. I've switched from using Oracle's Java to using [Microsoft's build of OpenJDK](https://www.microsoft.com/openjdk) instead. The benefits of OpenJDK are better multi-platform support, and no need to actually _install_ it. The only negative is a larger file size (oh well).

With the switch to OpenJDK, all external tools natively support OSX, Linux, and Windows-- All three on either system architecture (x64 and Arm64).

I've broken out _almost_ all platform-specific functionality into the platform layer, although a few tweaks still need to be made.

**Comment by blake502** [comment]
I've implemented speculative code for OSX and Linux for _most_ things. Only minor teaks necessary now to make full use of the platform layer.

At this point, I could use some help from Linux and MacOS developers to iron out the details.

Check out this branch: https://github.com/blake502/balatro-mobile-maker/tree/multi-platform

**Comment by CUexter** [comment]
i am a dedicated linux user, what can i help ?

**Comment by blake502** [comment]
Thanks for that info!

> Another thing, Personally i would not want to download the programs that i have already installed, maybe just try calling the command first and see if they are in PATH or not. Only download them when they arent there ?

That's the plan. For the moment, the "speculative" code assumes that Python is already installed. The only reason we can't easily do that on Windows is because calling "python" without python installed launches the Microsoft Store and prompts the user to download it from there. For that reason, I switched to using the embedded Python for Windows. As for Java, I switched to OpenJDK, which does not require and install. At the moment, the Windows build doesn't require any tools to be installed-- just downloaded and executed.

**Comment by blake502** [comment]
Linux x64 is up and running!! I've included the OSX build as well, although I'm not convinced it's working.

There are some caveats-- For example, ABD is not implemented on any system besides Windows x64.

Linux and OSX will require Python to be installed manually if you plan to build for iOS. (not applicable to Android build)

https://github.com/blake502/balatro-mobile-maker/releases/tag/beta-0.8-pre

**Comment by Enderteck** [comment]
Just tried the Linux x64, and it worked !

**Comment by CUexter** [comment]
pull-save.sh 
```bash
#!/bin/bash
#
set -e

exit_with_error() {
    echo "Error: $1"
    exit 1
}

adb shell rm -r /data/local/tmp/balatro
adb shell mkdir /data/local/tmp/balatro/
adb shell mkdir /data/local/tmp/balatro/files/
adb shell mkdir /data/local/tmp/balatro/files/1/
adb shell touch /data/local/tmp/balatro/files/settings.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/settings.jkr > /data/local/tmp/balatro/files/settings.jkr"
adb shell touch /data/local/tmp/balatro/files/1/profile.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/profile.jkr > /data/local/tmp/balatro/files/1/profile.jkr"
adb shell touch /data/local/tmp/balatro/files/1/meta.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/meta.jkr > /data/local/tmp/balatro/files/1/meta.jkr"
adb shell touch /data/local/tmp/balatro/files/1/save.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/save.jkr > /data/local/tmp/balatro/files/1/save.jkr"
adb pull /data/local/tmp/balatro/files/. ~/balatro/save/



# Define the directory where your saves are stored on your PC
PC_SAVE_DIR="$HOME/.steam/steam/steamapps/compatdata/2379780/pfx/drive_c/users/steamuser/AppData/Roaming/Balatro"

# Define the directory to store backups
BACKUP_DIR="$HOME/balatro/backup"

# Create a backup of the current saves with a timestamp
DATE=$(date +"%Y%m%d-%H%M%S")
mkdir -p "${BACKUP_DIR}" || exit_with_error "Failed to create backup directory"
tar -czf "${BACKUP_DIR}/save-backup-${DATE}.tar.gz" -C "${PC_SAVE_DIR}" . || exit_with_error "Failed to create backup archive"

cd "${PC_SAVE_DIR}" || exit_with_error "Failed to change directory to PC save directory"
[[ -d "1" ]] && rm -r "1"
[[ -d "2" ]] && rm -r "2"
[[ -d "3" ]] && rm -r "3"
[[ -f "settings.jkr" ]] && rm "settings.jkr"

# Now pull the latest save files from the Android device
mv ~/balatro/save/* ${PC_SAVE_DIR}

# Confirm completion
echo "Save files updated and backup created with timestamp: ${DATE}"
```

**Comment by CUexter** [comment]
push-save.sh

```bash
#!/bin/bash
#

adb shell rm -r /data/local/tmp/balatro
adb shell mkdir /data/local/tmp/balatro/
adb shell mkdir /data/local/tmp/balatro/files/
adb shell mkdir /data/local/tmp/balatro/files/1/
# adb shell mkdir /data/local/tmp/balatro/files/2/
# adb shell mkdir /data/local/tmp/balatro/files/3/
adb shell touch /data/local/tmp/balatro/files/settings.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/settings.jkr > /data/local/tmp/balatro/files/settings.jkr"
adb shell touch /data/local/tmp/balatro/files/1/profile.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/profile.jkr > /data/local/tmp/balatro/files/1/profile.jkr"
adb shell touch /data/local/tmp/balatro/files/1/meta.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/meta.jkr > /data/local/tmp/balatro/files/1/meta.jkr"
adb shell touch /data/local/tmp/balatro/files/1/save.jkr
adb shell "run-as com.unofficial.balatro cat files/save/game/1/save.jkr > /data/local/tmp/balatro/files/1/save.jkr"
# adb shell touch /data/local/tmp/balatro/files/2/profile.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/2/profile.jkr > /data/local/tmp/balatro/files/2/profile.jkr"
# adb shell touch /data/local/tmp/balatro/files/2/meta.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/2/meta.jkr > /data/local/tmp/balatro/files/2/meta.jkr"
# adb shell touch /data/local/tmp/balatro/files/2/save.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/2/save.jkr > /data/local/tmp/balatro/files/2/save.jkr"
# adb shell touch /data/local/tmp/balatro/files/3/profile.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/3/profile.jkr > /data/local/tmp/balatro/files/3/profile.jkr"
# adb shell touch /data/local/tmp/balatro/files/3/meta.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/3/meta.jkr > /data/local/tmp/balatro/files/3/meta.jkr"
# adb shell touch /data/local/tmp/balatro/files/3/save.jkr
# adb shell "run-as com.unofficial.balatro cat files/save/game/3/save.jkr > /data/local/tmp/balatro/files/3/save.jkr"
adb pull /data/local/tmp/balatro/files/. ~/balatro/save/


# Define the directory where your saves are stored on your PC
PC_SAVE_DIR="$HOME/.steam/steam/steamapps/compatdata/2379780/pfx/drive_c/users/steamuser/AppData/Roaming/Balatro"
# Define the directory to store backups
BACKUP_DIR="$HOME/balatro/backup/android"

# Create a backup of the current saves with a timestamp
DATE=$(date +"%Y%m%d-%H%M%S")
mkdir -p "${BACKUP_DIR}" || exit_with_error "Failed to create backup directory"
tar -czf "${BACKUP_DIR}/save-backup-${DATE}.tar.gz" -C ~/balatro/save . || exit_with_error "Failed to create backup archive"


TMP="$HOME/balatro/tmp/save/"
mkdir -p $TMP
cp -r $PC_SAVE_DIR/* $TMP
cd $TMP
rm -r Mods/*
cp -r $HOME/balatro/mobile-mods/* $TMP/Mods


adb shell rm -r /data/local/tmp/balatro
adb shell mkdir /data/local/tmp/balatro
adb shell mkdir /data/local/tmp/balatro/files
adb shell mkdir /data/local/tmp/balatro/files/save
adb shell mkdir /data/local/tmp/balatro/files/save/game
adb push $TMP* /data/local/tmp/balatro/files/save/game && adb shell am force-stop com.unofficial.balatro && adb shell run-as com.unofficial.balatro cp -r /data/local/tmp/balatro/files . && adb shell rm -r /data/local/tmp/balatro && adb kill-server

rm -r $TMP

echo "Saves have been pushed to android"
```

**Comment by CUexter** [comment]
this is what i am using for now

**Comment by blake502** [comment]
With MacOS and Linux being supported now, I'm going to close this ticket.

ADB implementation for OSX and Linus is on the to-do list!
