### ISSUE TITLE
New ipa with changed save path

### ISSUE THREAD

**Issue by Sheep975** [blake502/balatro-mobile-maker#27]
I found [this](https://love2d.org/forums/viewtopic.php?t=82894&start=10) article and it worked!
This change allows all iOS users to access their save data. Here is new ipa. 
Note that **previous saves will be reset!** This is because I don't know how to move saves to a new location.
<img src="https://github.com/blake502/balatro-apk-maker/assets/67822493/5a6a07ee-e470-4089-9c42-067ebd5c841d" width="50%">
[balatro_base.zip](https://github.com/blake502/balatro-apk-maker/files/14969541/balatro_base.zip)

**Comment by Cyphs** [comment]
Dang nice job. I was in the process of looking into this and getting started with getting everything setup in Xcode but you beat me to it. I thought we had to modify `NSSearchPathDirectory searchdir = NSApplicationSupportDirectory;` in ios.mm to `NSSearchPathDirectory searchdir = NSDocumentDirectory;`

**Comment by blake502** [comment]
Nice work! I'll get this worked out soon!

**Comment by blake502** [comment]
@Sheep975 Do you use Discord? I'd like you ask you about something privately

**Comment by Sheep975** [comment]
Yes. My user name is remi.085

**Comment by blake502** [comment]
Sorry for the delay on this! I've been without internet for a little while.

In any case, I swapped out the IPA here https://github.com/blake502/balatro-mobile-maker/releases/tag/Additional-Tools-1.0
