### ISSUE TITLE
EXE not opening for me

### ISSUE THREAD

**Issue by trickyt1992** [blake502/balatro-mobile-maker#33]
I get a quick flash of what looks like CMD prompt and thats it. have copied balatro.exe to the same folder as the exe. Running 64bit windows. not sure whats going on?

**Comment by CUexter** [comment]
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86

**Comment by blake502** [comment]
What version of Windows are you using?

**Comment by trickyt1992** [comment]
Windows 10, Nathan fixed it with this: To install missing framework,
download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86

Thanks very much

**Comment by blake502** [comment]
Ah darn it. I incorrectly assumed .NET Core was bundled with Windows updates-- But it seems that only the older .NET Framework is included. Since we're committed to Core now, I suppose I'll create a self-contained build. That'll increase the file size of the tool to about 15mb, but oh well.

**Comment by CUexter** [comment]
there are two solutions to this problem:
1. Tell the user to install it on their own
2. Bigger file size, I guess people won't mind

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by blake502** [comment]
Beta 0.7.1 uses self-contained build now. Installing the .NET Core runtime should not be necessary anymore.
