### ISSUE TITLE
External assets of mods not being supported 

### ISSUE THREAD

**Issue by CUexter** [blake502/balatro-mobile-maker#34]
I tried to install 2 mods but failed. It all involves accessing file that are not lua files. Maybe allow us to use external storage ?

[Jojo's Tarot Cards](https://www.nexusmods.com/balatro/mods/13)
[JoJo's Tarots](https://www.nexusmods.com/balatro/mods/10)

**Comment by blake502** [comment]
Mods are out-of-scope for this project. I'm not even sure if it's possible, [given this](https://github.com/blake502/balatro-mobile-maker/issues/11#issuecomment-2051884188). [Nativefs](https://github.com/EngineerSmith/nativefs) might not even support Android.

I'm open to exploring this myself at a later point, but there are some more important things I'd like to tackle with the project first.

**Comment by CUexter** [comment]
i want to know if external storage patch support this but i will try maybe on thursday.

**Comment by blake502** [comment]
I'd love to be wrong about this-- But I think that's an oversimplification of how it works.

I haven't looked in to this, mind you, so take this with a grain of salt.. I imagine full mod support would require a patched version of Steamodded that loads all the files from a location that would play nicely with Android.

If you're able to work this out, please let me know what you find. I'm open to making the necessary changes, or merging a PR.

**Comment by eszoke** [comment]
While it doesn't solve the issue of installing mods on the fly on an existing mobile install, and not sure how LUA mods would work.

But any straight asset replacement moda can still be used by just directly modifying the files balatro.exe (can change it to .zip) and using that modded exe with the APK/IPA maker.

Got a couple of card and enhancement texture replacements working on both Android and iOS.

**Comment by blake502** [comment]
So you're saying that the assets can just be packed into the exe, and do not need to be in the mods folder?

If that's the case, I can have Balatro Mobile Maker detect mods during the build process, and offer to automatically pack the assets with the mobile build.

**Comment by CUexter** [comment]
no it only happens to simple texture, one mod of mine allow some sounds to be played when a tarot card is used

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CUexter** [comment]
i am sorry, but i have fixed the problem, the problem being that mods that have a folder named Assets need to be named assets in ios and android.

which is kinda strange because on linux it works fine as well. 

so perhaps the most easy way is to turn any uppercase named folder to lowercase folder

**Comment by CUexter** [comment]
if you want you can close the issue

**Comment by blake502** [comment]
> i am sorry, but i have fixed the problem, the problem being that mods that have a folder named Assets need to be named assets in ios and android.
> 
> which is kinda strange because on linux it works fine as well.
> 
> so perhaps the most easy way is to turn any uppercase named folder to lowercase folder

Thanks for this info! I'll keep it in mind if we decide to implement official mod support.
