### ISSUE TITLE
Language selector doesn't work

### ISSUE THREAD

**Issue by giuseppeleo97** [blake502/balatro-mobile-maker#36]
Hello, I just tried to change the language to italian (my native language) and I noticed that the entire section doesn't work.

**Comment by blake502** [comment]
Just to be certain, are you using the latest build? This was an issue at one point, but I have no problem switching to Italian since this was fixed.

**Comment by giuseppeleo97** [comment]
I'm using beta-0.7.2 build with Balatro 1.0.0-n

**Comment by giuseppeleo97** [comment]
Anyways, congratulations for this incredible work

**Comment by blake502** [comment]
Thanks, but this is quite strange. Can you be absolutely certain that you've built a fresh APK, and have completely removed the previous version before installing the fresh APK?

**Comment by blake502** [comment]
I'll go ahead and close this issue. If you're absolutely sure you've built and installed a fresh APK using the latest version of the project, let me know and I'll reopen this issue.
