### ISSUE TITLE
Android constant crashing 

### ISSUE THREAD

**Issue by Bandix123** [blake502/balatro-mobile-maker#37]
So I boot up the game, sometimes even on the title screen it crashes.
But usually I can play one hand before it quits from the app and goes into an infinite loop of exiting the game (no error message or nothing)

Tried to rebuild the app in different ways, same result

Samsung galaxy a52

**Comment by blake502** [comment]
This is really tricky to debug without more info. You can look for more information with logcat, though I'm not sure how much information that'll give us.

It's possible your device isn't powerful enough.

**Comment by blake502** [comment]
Closing issue. I'll reopen if you can provide more information about this.

For what it's worth-- If you're playing on a non-English language, it may help to switch to English (or a language with a similar character set)
