### ISSUE TITLE
Latest buil 0.7.2 timing out

### ISSUE THREAD

**Issue by Jeffdak1lla** [blake502/balatro-mobile-maker#38]
![Screenshot_2024-04-15-17-49-12-90_965bbf4d18d205f782c6b8409c5773a4~2](https://github.com/blake502/balatro-mobile-maker/assets/19418377/ddc43127-fd34-4207-80b6-f4ed654e4705)

**Comment by blake502** [comment]
Looks like [APKTool](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar) is failing to download. Can you attempt to download it manually using that link? You'll need to trim the version name off the file you download, it should just be called `apktool.jar`. Place it in the same directory as the Balatro-Mobile-Maker and try again.

**Comment by Jeffdak1lla** [comment]
that worked, thanks!

**Comment by blake502** [comment]
It's quite strange that it was timing out in the first place-- Usually that means your connection is poor, or the link is blocked by your network admins. In any case, I'm glad it's working now. Have a great day!
