### ISSUE TITLE
Trojan detected in exe

### ISSUE THREAD

**Issue by KnoBuddy** [blake502/balatro-mobile-maker#39]
![image](https://github.com/blake502/balatro-mobile-maker/assets/64171756/bb02342a-634e-4bb0-979c-98fee84cb40c)

https://www.virustotal.com/gui/file/b06beeb0116f23b271122767f0be842dd5c5082b1e585e79ded01985a8fe0036/detection

**Comment by blake502** [comment]
There is no virus in this project. Don't take my word for it— review the code and build it for yourself.

Plugging small-scale, open source software into virustotal is going to give you false positives.

**Comment by KnoBuddy** [comment]
> See [duplicate](https://github.com/blake502/balatro-mobile-maker/issues/10)

I saw the other issue, I literally couldn't even download the file in chrome and I have safe browsing turned off. I had to disable windows security as well. Just commenting, because I feel this should be addressed. Would just make everything a bit cleaner overall, it's not something I'd want if it were me publishing the software, obviously if it cannot be avoided, that's understandable.

By the way, I went ahead and installed it and ran it on my android phone almost immediately after posting this, before your reply, making the assumption it is a false positive. I'm very impressed to say the least, and I intend to look at the source when I have some time because you've done some amazing work here. I'm assuming it's because it's based on the LOVE engine? Guess the source will tell me everything I need to know.

**Comment by blake502** [comment]
I'll re-open this to see what I can do about it. Unfortunately, I have no control over what VirusTotal, Chrome, or Windows Defender consider to be a virus.

**Comment by UScr00ge** [comment]
Yeah, Bitdefender flagged it too. I ignored it :)

**Comment by blake502** [comment]
I've created a build that only trips Bkav Pro. I've reached out to the Bkav Pro team to see whether an exception can be made.

I'm not incredibly hopeful, but at least we can probably keep Chrome and Windows Defender from flagging it.
