### ISSUE TITLE
Android UI elements overlapping each other

### ISSUE THREAD

**Issue by jeffcampbell** [blake502/balatro-mobile-maker#40]
The apk works fine, but when I run the app the UI elements are all grouped together in the middle of the screen. This may be specific to my device (Pixel 8 Pro). I was wondering if anyone else has seen this and if there's a potential fix? Thanks!
![Screenshot_20240417-072253](https://github.com/blake502/balatro-mobile-maker/assets/4997935/68f37d4c-7e4f-4cb6-a4e5-7c7151d3779c)

**Comment by blake502** [comment]
Which patches are you using? I ran into this during testing, but I do not recall exactly which patch corrected it.

I would apply the landscape patch, but not the HighDPI patch.

**Comment by jeffcampbell** [comment]
I figured it out. I was not on the public beta in Steam for 1.0.1c. This UI error only happens on the current stable build (1.0.0n). Once I switched builds everything was fixed. Maybe a "you need to use the experimental branch" warning should be added to the README?
