### ISSUE TITLE
Empty save folder in android

### ISSUE THREAD

**Issue by zegaton** [blake502/balatro-mobile-maker#41]
I want to copy and move my save in my Android balatro game to the balatro game in my PC, however when I try to find my save file in android/data/com.unoffical.balatro, the save folder is empty. Is the save stored somewhere else or do I have to reinstall? Afraid of losing my progress.
![Screenshot_2024-04-18-16-24-27-298_com google android documentsui](https://github.com/blake502/balatro-mobile-maker/assets/167414160/e61b9912-539a-4c6e-8b2f-1773596ef3cb)

**Comment by kletellier** [comment]
For me it works when you delete the empty folders, in the other way from steam to android you need to clear the app data before syncing with the exe

**Comment by zegaton** [comment]
> For me it works when you delete the empty folders, in the other way from steam to android you need to clear the app data before syncing with the exe

So delete the folders in com.unoffical.balatro, would this delete my save?

**Comment by kletellier** [comment]
Yes, but in this case (android to steam) copy with the exe procedure and remove the empty folders on your steam computer

**Comment by blake502** [comment]
See my response here: https://github.com/blake502/balatro-mobile-maker/issues/29#issuecomment-2054245361

That folder being empty is a question for the Android developers. The occurs even with the old "accessible saves" patch-- which was named speculatively before I realized that it was no easier to access that location, unless maybe you have root access. That said, since the "accessible saves" patch is gone (bad idea in the first place), that's not the proper location anymore.

You should be looking here: `/data/data/com.unofficial.balatro/files/save/`
That said-- that directory is only accessible with ADB as far as I know.

**Comment by blake502** [comment]
I'll go ahead and close this issue to clean up the list, but I'll re-open if you need more support with this.

**Comment by r3conx** [comment]
Maybe "Shizuku" will help here?

**Comment by blake502** [comment]
I've tried, and it did not yield any different results for me unfortunately-- but I say go for it if you have the patience to try.

**Comment by zegaton** [comment]
aw shucks

**Comment by zegaton** [comment]
> See my response here: [#29 (comment)](https://github.com/blake502/balatro-mobile-maker/issues/29#issuecomment-2054245361)
> 
> That folder being empty is a question for the Android developers. The occurs even with the old "accessible saves" patch-- which was named speculatively before I realized that it was no easier to access that location, unless maybe you have root access. That said, since the "accessible saves" patch is gone (bad idea in the first place), that's not the proper location anymore.
> 
> You should be looking here: `/data/data/com.unofficial.balatro/files/save/` That said-- that directory is only accessible with ADB as far as I know.
> 
> Edit: Balatro Mobile Maker has the option to _pull_ your saves from your Android device through ADB-- But that will not work if your game was created with the old "accessible saves" patch.

Thanks a lot, I'll try to figure out the ADB stuff since I'm not used to android debugging.

**Comment by RobinDeFloof** [comment]
Nothing I seem to do will get the balatro saves onto my phone, the data is on my phone (I manually put them on there in a random folder), I just can't find the folder for it (and I can't use my computer since I won't be home for a few days)
