### ISSUE TITLE
how to handle iOS save ?

### ISSUE THREAD

**Issue by CUexter** [blake502/balatro-mobile-maker#42]
how to handle iOS save ? I have no idea how iOS work

**Comment by blake502** [comment]
Check this out: https://github.com/blake502/balatro-mobile-maker/issues/27

Try building the app again using the latest version of the tool. Be sure to clear out the folder before running the tool again!

While I'm not particularly knowledgeable with iOS-- as I understand, this will put your saves in an accessible location in your Documents folder?

I'll close this issue for now, but let me know if it gives you trouble and I'll re-open.

**Comment by CUexter** [comment]
works great, even better than android as i can manage the mods and save file directly from the files app. I wish android can do that as well
