### ISSUE TITLE
Want Accessible Saves

### ISSUE THREAD

**Issue by PratyushChhipa** [blake502/balatro-mobile-maker#43]
Can you please add optional patch for accessible saves again for android if it is not a problem because adb crashes my phone it is problematic to me. So, can you please add it again

**Comment by blake502** [comment]
See my comment here: https://github.com/blake502/balatro-mobile-maker/issues/29

The accessible saves patch was a poor naming decision, as it did not make the saves more accessible whatsoever. It simply changed the storage location to the emulated sdcard. On recent versions of Android, that location still requires ADB to access, so the patch was removed.

If you'd like to experiment, that patch is still in the code-- Just disabled. You can build the project for yourself to try it out.

**Comment by PGgamer2** [comment]
What about readding the accessible saves patch but enabling it through command line arguments?
Something like `./balatro-mobile-maker-beta-0.7.3-win-x64.exe --enable-accessible-patch`: it stays hidden, but it's still available

**Comment by PratyushChhipa** [comment]
Can you please guide me a little on how to enable accessible saves patch because I can access the older location without adb

**Comment by PratyushChhipa** [comment]
Because I have a lite older android

**Comment by antipatico** [comment]
> Can you please guide me a little on how to enable accessible saves patch because I can access the older location without adb

You can add it editing [this line of code](https://github.com/blake502/balatro-mobile-maker/blob/8913e3d73d760ddace2ab67fec6184a674c66cc8/balatro-mobile-maker/Patching.cs#L137) removing the `false &&` from the if.

> What about readding the accessible saves patch but enabling it through command line arguments? Something like `./balatro-mobile-maker-beta-0.7.3-win-x64.exe --enable-accessible-patch`: it stays hidden, but it's still available

I did that for my project and it should be possible to also do that in C#! I would like to help but I am not a C# expert. That being said, I was experimenting on love-android, trying to bring the saves on accessible folder back by other means, without luck. Unfortunately, PhysFS and SDL do not play nice with Android. I am trying to reach out to love developers and see if it is in the realm of possibility adding import / export for save files.

Finally, there was a good discussion on issue number 4 of my fork about adding support to Storage Access Framework [[1](https://wiki.termux.com/wiki/Internal_and_external_storage)][[2](https://developer.android.com/guide/topics/providers/document-provider)]. It seems feasible, but then you would be able to import and export game files only on the Android device itself.

**Comment by blake502** [comment]
> What about readding the accessible saves patch but enabling it through command line arguments? Something like `./balatro-mobile-maker-beta-0.7.3-win-x64.exe --enable-accessible-patch`: it stays hidden, but it's still available

Good call, I can do this. I wanted to wait on doing any command line args until I had a better idea of our wants/needs for it. Plus I've been a little distant on this project for a few days since my internet was out haha.

> Can you please guide me a little on how to enable accessible saves patch because I can access the older location without adb

I hate to be a pessimist-- But I still don't think it'll work the way you expect. You can "_access_" the folder, but it will appear empty unless you use ADB.

**Comment by blake502** [comment]
Try Beta-0.7.3 with this command line argument `--enable-external-storage-patch`

**Comment by CUexter** [comment]
is there a way to make it not require adb ?

**Comment by PratyushChhipa** [comment]
> Try Beta-0.7.3 with this command line argument `--enable-external-storage-patch`

It works thanks

**Comment by blake502** [comment]
> is there a way to make it not require adb ?

Probably not. While it _is_ quite annoying, it's important to understand that it's a security feature of Android. Imagine if it were that easy to manipulate the information from your banking app, for example. The only reason we can even do it over ADB is because the app is built with the "debug" flag enabled, which allows us to manipulate the files through ADB commands _as if_ it were the app making the request.

**Comment by KaiserCalm** [comment]
> Try Beta-0.7.3 with this command line argument `--enable-external-storage-patch`

This is an amazing feature! Could it be possibly documented in the README?
