### ISSUE TITLE
Can't select lenguages other than english

### ISSUE THREAD

**Issue by Xedric-Dev** [blake502/balatro-mobile-maker#47]
Is known that Balatro is translated in several lenguages, so i'm asking why in the app we cannot select them.

**Comment by blake502** [comment]
This was fixed in https://github.com/blake502/balatro-mobile-maker/pull/3

Are you sure you've built the app using the latest version?

Which version of Balatro Mobile Maker are you using? Which version of Balatro are you using?
Which platform are you running Balatro Mobile Maker on? Which platform are you running the mobile app on?

**Comment by Xedric-Dev** [comment]
I used the latest build (beta-0.7.4) and the 1.0.0 of Balatro. I used your app in Windows 11 and installed and run the apk on Google Pixel 7a. Also i used all the patch of your app.

And here the video : https://drive.google.com/file/d/1Y6hgipBSdOTVrCucmJwznBar2bOkwwq7/view?usp=drivesdk

**Comment by CUexter** [comment]
i can't view the video, also can you select other languages in the original build on pc ? just to make sure your exe is not corrupted. 

I can select languages on both my ios and android device

**Comment by Xedric-Dev** [comment]
Sorry, now you can see it.... And yes i can select them, in playing in italian on pc

**Comment by CUexter** [comment]
no I think you have to post a new link

**Comment by Xedric-Dev** [comment]
I'm not expert in sharing video file ahahha. I hope this work: https://www.dropbox.com/scl/fi/8zvwx2hc4i7at41vbkh5z/BalatroApk_Lang_Bug.mp4?rlkey=vqpwkjlrijm2kwjx43v9pgeox&st=3tchesxb&dl=0

**Comment by CUexter** [comment]
U should update balatro on steam

**Comment by Xedric-Dev** [comment]
Yeah, i update it now and it worked with balatro  v.1.0.1e, my fault that i disabled the auto update on steam. Sorry for wasting your time, and thanks.

**Comment by blake502** [comment]
No worries, I'm glad it's working now.
