### ISSUE TITLE
Installing via USB debugging on Pixel 6a doesn't work

### ISSUE THREAD

**Issue by SSCminion** [blake502/balatro-mobile-maker#48]
On the most recent stable build (0.7.4) when trying to do automatic install via USB debugging on my Pixel 6a, it doesn't install. Tried multiple times and just didn't work.

My temporary workaround is I just built the APK, manually installed it, then re-ran the builder (skipping the build process) and then transferred the saves over to my phone.

Just for clarity, the save transferring worked, just not the automatic install

**Comment by blake502** [comment]
Can you run it with extra logging enabled and let me know what error message you receive?

**Comment by SSCminion** [comment]
For whatever reason that is beyond me, when I tried to reproduce the bug, I couldn't. The APK automatically installs perfectly fine now. Yesterday when I was trying to debug the problem I restarted my phone, tried it with and without certain patches and nothing worked. Maybe restarting my PC fixed it?

**Comment by blake502** [comment]
Strange. Maybe just a quirk with ADB.

In any case, I'm glad it's working now. Have a great day!
