### ISSUE TITLE
Error patching landscape and high DPI modes

### ISSUE THREAD

**Issue by Pandorify** [blake502/balatro-mobile-maker#58]
Applying the landscape and high DPI patches gives the error 'Unable to find patch location'  after loading .lua file. Same issue across multiple version of Balatro with no change running as administrator. 
![image](https://github.com/blake502/balatro-mobile-maker/assets/104906482/789bbfe2-2cb2-4982-9b86-fef86a4b6f2a)

**Comment by blake502** [comment]
Which version of Balatro are you using?

**Comment by Pandorify** [comment]
I've tried 1.0.1c and 1.0.1e, I tried patching on another PC and didn't have the issue.

**Comment by blake502** [comment]
Sorry for the delay on this. Sounds like something may have been corrupt on the first PC you tried.
I'll go ahead and close this, but I'll gladly re-open if you can recreate the issue.
