### ISSUE TITLE
Trouble executing this on ARM64 mac

### ISSUE THREAD

**Issue by rossmessing** [blake502/balatro-mobile-maker#59]
I'm trying to run the arm64 release on an m1 mac, and I'm getting errors saying it can't be opened / doesn't know how to open it.  Are there frameworks that need to be installed in order to execute the mac version?

Sorry to raise this sort of thing in an issue, but not sure where to ping. 

The release download looks like a file whose format the system doesn't recognize. 

Can confirm the same behavior on an x86 Mac as well.

**Comment by kylefmohr** [comment]
Are you just double-clicking the file? You'll likely need to open Terminal, change directory to your Downloads folder (`cd ~/Downloads`), and run `./<the file you downloaded`, so `./balatro-mobile-maker-beta-0.8.2-osx-arm64-expeimental`. 

If that doesn't work, try a `chmod +x balatro-mobile-maker-beta-0.8.2-osx-arm64-expeimental` and then run the previous command I mentioned.

**Comment by rossmessing** [comment]
> Are you just double-clicking the file? You'll likely need to open Terminal, change directory to your Downloads folder (`cd ~/Downloads`), and run `./<the file you downloaded>`, so `./balatro-mobile-maker-beta-0.8.2-osx-arm64-expeimental`. 
> 
> 
> 
> If that doesn't work, try a `chmod +x balatro-mobile-maker-beta-0.8.2-osx-arm64-expeimental` and then run the previous command I mentioned.

It gave me some kind of permissions issue (unknown app signer), even with 'sudo'. I'll dig in and report more tomorrow. But thanks for confirming that it is, in fact, an executable that should work without any extra stuff installed.

**Comment by kylefmohr** [comment]
oh sure, I think I know how to fix that too: try `sudo xattr -cr balatro-mobile-maker-beta-0.8.2-osx-arm64-expeimental`, then try rerunning it

**Comment by rossmessing** [comment]
Updates:
* I couldn't make it work on my arm64 mac.  
* It's a me-specific thing - machine has some security-ware preventing it.  This shouldn't be an issue for other users.  Can close the issue.
* WAS able to get it working on my intel mac.  Haven't tried using the apks yet (tomorrow), but it built them just fine.
* Note that I had to dig into the Balatro app to find the Balatro.love file in Contents to make this work (just copied it to the same dir as the apk-maker.

**Comment by rossmessing** [comment]
Update:

Can confirm the app generated on the Intel Mac works on an android device. 

Sadly, can also confirm the text is a little too small to read on a retroid pocket 2+, whether or not high-dpi mode is enabled.

**Comment by kylefmohr** [comment]
> Note that I had to dig into the Balatro app to find the Balatro.love file in Contents to make this work (just copied it to the same dir as the apk-maker.

Yeah I opened a PR earlier today that should fix this! Glad you got it somewhat working, but yeah, I can imagine text size would be an issue on a smaller screen.

**Comment by blake502** [comment]
Changes from PR #61 now in the latest release.

**Comment by blake502** [comment]
> Sadly, can also confirm the text is a little too small to read on a retroid pocket 2+, whether or not high-dpi mode is enabled.

Feel free to open another issue about this point. As for this one, I'll go ahead and close it.

**Comment by lukewalbeck** [comment]
I'm running into the same issue on 0.8.3 on my M1 Mac, OS 14.3

```
> chmod +x ./balatro-mobile-maker-beta-0.8.3-osx-arm64-expeimental
> sudo xattr -cr balatro-mobile-maker-beta-0.8.3-osx-arm64-expeimental
> ./balatro-mobile-maker-beta-0.8.3-osx-arm64-expeimental
[1]    20293 killed     ./balatro-mobile-maker-beta-0.8.3-osx-arm64-expeimental
```

Am I missing anything?

**Comment by lukewalbeck** [comment]
What DID work was running the `UNTESTED-balatro-mobile-maker-beta-0.8.3-osx-x64` one on my M1 Mac. A bit odd, but glad I was able to use the tool!

**Comment by blake502** [comment]
Wonderful, I'll consider osx-x64 as "experimental" instead of "untested" now :)
