### ISSUE TITLE
Save data not transferring onto IOS 

### ISSUE THREAD

**Issue by CoffeeDoster** [blake502/balatro-mobile-maker#64]
Not sure if I'm doing something wrong. The game itself works amazing (awesome work btw) but I was wondering if it was possible to transfer save data to IOS. Nothing has been mentioned in issues or the description, so I wasn't sure if it was an android exclusive thing.

**Comment by kylefmohr** [comment]
It isn't currently supported via the script, and I'm not sure of a way to add this as a feature, however I can tell you that it is possible to manually transfer your save. The method of enabling this, however, will vary based on what tool you're using to sign the IPA file.

For example, if you're using Sideloadly, you'll simply need to click `Advanced Options` and check the box for `Enable File Sharing`. If instead you're using ESign to sign the app on-device, you'll need to click `More Settings` then `Supports Document Browser`. SignTools also has an option under `Advanced` called `Force enable file sharing`. 

Once you've installed the app with file sharing enabled, you'll be able to see a `Balatro` folder in the Files app on your iDevice. It should look exactly like the Balatro save directory on your computer, just move those save files over from your computer and restart the app. I can confirm this works with the most recent Balatro update. 

I wish there were a way to automate this, but I don't know of any way to do so.

**Comment by clwang714** [comment]
Syncing the save files between iOS and PC can be automated, although it will take some jank to setup:

**PC Setup:**

1. Setup iCloud Drive for Desktop
2. Move your Balatro save folder to iCloud Drive
3. Create a symlink on your PC from your old save location to your new iCloud Drive save location

Your PC can now read and write save data directly to iCloud Drive.

--------------------------------------------

**iOS Setup:**

1. Sideload the Balatro IPA
2. Open the app once so that it can create a Balatro save folder in your Files app (locally on your device, not in iCloud Drive)
    - if you are jailbroken, you can use Filza to create a symlink from this local folder to your new save folder in iCloud and skip the rest of the steps

For non-JB, we will have to create some shortcuts to automatically sync this data to iCloud:

**Pushing to iCloud:**

3. Create a new Shortcut using `Get contents of folder` (select your local save folder) and `Save File` (select your iCloud save folder). This will copy your local save from phone to iCloud, so your PC will have the updated save data
    - `Recursive` - no, `Ask Where To Save` - no, `Overwrite If File Exists` - yes
5. Create a Shortcuts automation to run this shortcut when Balatro app is closed

**Fetching from iCloud**

4. Create the same Shortcut as above but reverse the two folders
6. Add another step to the Shortcut to launch the Balatro app. Then add the shortcut to the home screen (you can change the icon). Use this shortcut to launch the game, instead of the actual app
    - (we can't use Shortcuts automations like above, because running the shortcut after Balatro is already launching is not fast enough. the game finishes launching before data is synced)

**Comment by jawshoeadan** [comment]
Using pymobiledevice3 would be an easier way of doing the same thing, where you can use AFC to push the saves folder to the device, but you’d have to use the script to build the ipa, then sideload it through whichever method, then come back to the script to copy the saves over

**Comment by zgr0629** [comment]
> Syncing the save files between iOS and PC can be automated, although it will take some jank to setup:
> 
> **PC Setup:**
> 
> 1. Setup iCloud Drive for Desktop
> 2. Move your Balatro save folder to iCloud Drive
> 3. Create a symlink on your PC from your old save location to your new iCloud Drive save location
> 
> Your PC can now read and write save data directly to iCloud Drive.
> 
> **iOS Setup:**
> 
> 1. Sideload the Balatro IPA
> 2. Open the app once so that it can create a Balatro save folder in your Files app (locally on your device, not in iCloud Drive)
>    
>    * if you are jailbroken, you can use Filza to create a symlink from this local folder to your new save folder in iCloud and skip the rest of the steps
> 
> For non-JB, we will have to create some Shortcuts to automatically sync this data to iCloud:
> 
> **Pushing to iCloud:**
> 
> 3. Create a new Shortcut using `Get contents of folder` (select your local save folder) and `Save File` (save "Contents of Folder" to your iCloud save folder). This will copy your local save from phone to iCloud, so your PC will have the updated save data
>    
>    * `Recursive` - no, `Ask Where To Save` - no, `Overwrite If File Exists` - yes
> 4. Create a Shortcuts automation to run this shortcut when Balatro app is closed
> 
> **Fetching from iCloud**
> 
> 4. Create the same Shortcut as above but reverse the two folders
> 5. Add another step to the Shortcut to launch the Balatro app. Then add the shortcut to the home screen (you can change the icon). Use this shortcut to launch the game, instead of the actual app
>    
>    * (we can't use Shortcuts automations like above, because running the shortcut after Balatro is already launching is not fast enough. the game finishes launching before data is synced)
> 
> Note that the game only updates the save file intermittently, which can lead to problems with save data syncing. I always make sure to exit to main menu, which seems to force a save. Also, if you are having issues, try to wait at least 15-20 seconds after closing the game before launching it on a different device to ensure that the iCloud sync completes. I always kill the app as well to be super safe

Great idea. I use "When Balatro is closed" automation to push to iCloud and it works great.

**Comment by mershonc** [comment]
> It isn't currently supported via the script, and I'm not sure of a way to add this as a feature, however I can tell you that it is possible to manually transfer your save. The method of enabling this, however, will vary based on what tool you're using to sign the IPA file.
> 
> For example, if you're using Sideloadly, you'll simply need to click `Advanced Options` and check the box for `Enable File Sharing`. If instead you're using ESign to sign the app on-device, you'll need to click `More Settings` then `Supports Document Browser`. SignTools also has an option under `Advanced` called `Force enable file sharing`.
> 
> Once you've installed the app with file sharing enabled, you'll be able to see a `Balatro` folder in the Files app on your iDevice. It should look exactly like the Balatro save directory on your computer, just move those save files over from your computer and restart the app. I can confirm this works with the most recent Balatro update.
> 
> I wish there were a way to automate this, but I don't know of any way to do so.

I am not seeing anything in the balatro game files that were created by my steam .api i created with your tool other than Balatro > game > then there is a "settings.jkr" and a folder that is titled "1", when clicking on that folder it shows the following: profile.jkr, save.jkr, and meta.jkr -- Nothing in the save folder local on my iphone created by the game resembles what the actual steam game files look like! Am I doing something wrong? I used sideloadly to push the api to my iphone.

**Comment by kylefmohr** [comment]
> Syncing the save files between iOS and PC can be automated, although it will take some jank to setup:
> 
> 
> 
> **PC Setup:**
> 
> 
> 
> 1. Setup iCloud Drive for Desktop
> 
> 2. Move your Balatro save folder to iCloud Drive
> 
> 3. Create a symlink on your PC from your old save location to your new iCloud Drive save location
> 
> 
> 
> Your PC can now read and write save data directly to iCloud Drive.
> 
> 
> 
> --------------------------------------------
> 
> 
> 
> **iOS Setup:**
> 
> 
> 
> 1. Sideload the Balatro IPA
> 
> 2. Open the app once so that it can create a Balatro save folder in your Files app (locally on your device, not in iCloud Drive)
> 
>     - if you are jailbroken, you can use Filza to create a symlink from this local folder to your new save folder in iCloud and skip the rest of the steps
> 
> 
> 
> For non-JB, we will have to create some Shortcuts to automatically sync this data to iCloud:
> 
> 
> 
> **Pushing to iCloud:**
> 
> 
> 
> 3. Create a new Shortcut using `Get contents of folder` (select your local save folder) and `Save File` (save "Contents of Folder" to your iCloud save folder). This will copy your local save from phone to iCloud, so your PC will have the updated save data
> 
>     - `Recursive` - no, `Ask Where To Save` - no, `Overwrite If File Exists` - yes
> 
> 5. Create a Shortcuts automation to run this shortcut when Balatro app is closed
> 
> 
> 
> **Fetching from iCloud**
> 
> 
> 
> 4. Create the same Shortcut as above but reverse the two folders
> 
> 6. Add another step to the Shortcut to launch the Balatro app. Then add the shortcut to the home screen (you can change the icon). Use this shortcut to launch the game, instead of the actual app
> 
>     - (we can't use Shortcuts automations like above, because running the shortcut after Balatro is already launching is not fast enough. the game finishes launching before data is synced) 
> 
> 
> 
> ----------------------------
> 
> 
> 
> Note that the game only updates the save file intermittently, which can lead to problems with save data syncing. I always make sure to exit to main menu, which seems to force a save. Also, if you are having issues, try to wait at least 15-20 seconds after closing the game before launching it on a different device to ensure that the iCloud sync completes. I always kill the app as well to be super safe
> 
> 

This is clever, I hadn't considered a shortcut that runs on close. I'm gonna play around with that a bit.

**Comment by Zelatrix23** [comment]
> > It isn't currently supported via the script, and I'm not sure of a way to add this as a feature, however I can tell you that it is possible to manually transfer your save. The method of enabling this, however, will vary based on what tool you're using to sign the IPA file.
> > For example, if you're using Sideloadly, you'll simply need to click `Advanced Options` and check the box for `Enable File Sharing`. If instead you're using ESign to sign the app on-device, you'll need to click `More Settings` then `Supports Document Browser`. SignTools also has an option under `Advanced` called `Force enable file sharing`.
> > Once you've installed the app with file sharing enabled, you'll be able to see a `Balatro` folder in the Files app on your iDevice. It should look exactly like the Balatro save directory on your computer, just move those save files over from your computer and restart the app. I can confirm this works with the most recent Balatro update.
> > I wish there were a way to automate this, but I don't know of any way to do so.
> 
> I am not seeing anything in the balatro game files that were created by my steam .api i created with your tool other than Balatro > game > then there is a "settings.jkr" and a folder that is titled "1", when clicking on that folder it shows the following: profile.jkr, save.jkr, and meta.jkr -- Nothing in the save folder local on my iphone created by the game resembles what the actual steam game files look like! Am I doing something wrong? I used sideloadly to push the api to my iphone.

In case anyone wants a solution to this, the .jkr files that Steam uses are saved in "C:\Users\user\AppData\Roaming\Balatro" (at least for me). So I uploaded those to iCloud, and have my IOS Balatro save and read those files.
