### ISSUE TITLE
com.unofficial.balatro/files folder empty

### ISSUE THREAD

**Issue by nIIksa** [blake502/balatro-mobile-maker#70]
I wanted to transfer my save files from android, but my com.unofficial.balatro/files folder is empty for some reason. Where can i find my saves?

**Comment by blake502** [comment]
That's correct. You're not looking in the correct location for saves. The correct location can only be accessed via ADB, or with root access.

Can you use the save transfer feature built in to the project?

**Comment by nIIksa** [comment]
I transfered steam saves, but i dont know how to transfer from android.

**Comment by nIIksa** [comment]
Okay, i did it.
