### ISSUE TITLE
Possible Malware in the APK file

### ISSUE THREAD

**Issue by sanebg** [blake502/balatro-mobile-maker#73]
VirusTotal detected 2 issues 

PUP/Android.Malct.1190475

Android.PUA.DebugKey

While Android PUA Debug Key isn't something that's an issue, the Android.Malct is another topic. It's practically a very nasty backdoor into our phones.

**Comment by udayvir-singh** [comment]
@sanebg PUP just means Potentially Unwanted Program, it is probably marking it as such because the apk is not signed by a verified key.

**Comment by kylefmohr** [comment]
[Can't reproduce](https://www.virustotal.com/gui/file/ebc2dcf65a02b60e0f81191455e1047ed453dbbd7a353702a23f338d57a19cef?nocache=1), maybe the false positive has been fixed

**Comment by blake502** [comment]
[I was able to reproduce.](https://www.virustotal.com/gui/file/66872555f0a7aafe9bdceadc6a3d888c61265a4a739f187710c680a1352fdf55)

Unfortunately there's nothing I can do about false positives. I certainly admire you taking your device security seriously, but the best course of action is to review the code for yourself.
