### ISSUE TITLE
How to transfer save data back to PC?

### ISSUE THREAD

**Issue by YR1044** [blake502/balatro-mobile-maker#74]
I just successfully transfered my Steam save data to my Andriod phone and played a few days

And now I wish I could transfer my newer save data to my PC, my phone doesn't have a root permisson, is there any chance to do that?

**Comment by kylefmohr** [comment]
@YR1044 I think this is already built-in to Balatro-Mobile-Maker, just rerun the binary, pretend like you're building it for Android again, but this time, when it asks `Would you like to transfer saves from your Steam copy of Balatro to your Android device?`, choose no, and it will then ask `Would you like to pull saves from your Android device?`, choose yes.

**Comment by YR1044** [comment]
> @YR1044 I think this is already built-in to Balatro-Mobile-Maker, just rerun the binary, pretend like you're building it for Android again, but this time, when it asks , choose no, and it will then ask , choose yes.`Would you like to transfer saves from your Steam copy of Balatro to your Android device?``Would you like to pull saves from your Android device?`

Yeah you are right, thanks a lot.
But I notice that my "Mods" dir in my PC was deleted after this action, maybe I should make a backup next time

**Comment by blake502** [comment]
> But I notice that my "Mods" dir in my PC was deleted after this action, maybe I should make a backup next time
```
Have you backed up your saves? (y/n):
y
```
That's the purpose of this prompt.
BMM automatically backs up your saves before transfer, but you should not rely on that feature. You can check for your missing files in this location: `%appdata%\BalatroBACKUP\`
