### ISSUE TITLE
How to run this script on Linux

### ISSUE THREAD

**Issue by VladDanger97** [blake502/balatro-mobile-maker#79]
I tried so hard to start it but nothing worked

**Comment by blake502** [comment]
The same as any other Linux binary.
Use `chmod +x` to enable execution.
Then `./balatro-apk-maker` to run it.

What have you tried? What kind of error do you see?

**Comment by VladDanger97** [comment]
Most likely I just haven’t figured out Linux and now I’m just sitting on Windows

**Comment by zachs18** [comment]
For me, this worked on Ubuntu 24.04:

```sh
$ sudo apt install dotnet8
$ // cd to source directory
$ dotnet msbuild
$ cp /path/to/steamapps/common/Balatro/Balatro.exe .
$ ./balatro-mobile-maker/bin/Debug/net8.0/balatro-mobile-maker
```
