### ISSUE TITLE
Stuck on tutorial seed

### ISSUE THREAD

**Issue by GayCoonie** [blake502/balatro-mobile-maker#89]
I'm not 100% sure that this isn't just how new installs work until you beat the tutorial seed, but I couldn't find any references online to that being the case. Basically, I can't seem to get the game to start an actual normal run. No matter how many times I intentionally lose or restart the run, it's still the tutorial seed. I'm on whatever the most recent Android version is for the Note 20 Ultra, and I transferred my legit steam install from Linux (Mint 21.3)

**Comment by Dimserene** [comment]
You'll need to play enough rounds (no need to win the tutorial seed) to get pass it

**Comment by GayCoonie** [comment]
> You'll need to play enough rounds (no need to win the tutorial seed) to get pass it

Thank you that worked. Total user error, lol

**Comment by Spaagz** [comment]
How many rounds does this have to be?
